version: 0.6

logging:
  level: INFO
  format: "%(levelname)s:%(name)s:%(message)s"

scenario:
  resarea: [redz, corridors]
  regions: ['RSA','9-supply','27-supply'] # Resolution 1-node, 9 provinces, 27 Eskom supply areas 
  costs: [Ambitions] 
  opts: [LC, Co2L] # , EP, BAU, LC-SAFE, Co2L-SAFE] #, LC-FL, LC-T, Ep-T, Co2L-T]
  ll: ['copt']

data:
  resarea:
    redz: REDZ_DEA_Unpublished_Draft_2015
    corridors: Power_corridors
  supply_regions:
    shapes: data/supply_regions_new/RSA_single.shp
    centroids: 'data/supply_regions_new/centroid_RSA_single.shp'

# definition of the Coordinate Reference Systems
crs:
  geo_crs: EPSG:4326  # general geographic projection, not used for metric measures. "EPSG:4326" is the standard used by OSM and google maps
  distance_crs: EPSG:3857  # projection for distance measurements only. Possible recommended values are "EPSG:3857" (used by OSM and Google Maps)
  area_crs: ESRI:54009  # projection for area measurements only. Possible recommended values are Global Mollweide "ESRI:54009"

years: [2025,2030,2035,2040]
base_demand_year: 2012
base_weather_years: [2012]
historical_year: "2012"

electricity:
  demand: 428.e+6     # 344TWh 2030, 428TWh 2040, 522TWh 2050
                      # IRP_Update_Assumptions_1904.pdf
  co2limit: 50.e+6    # 470.9e+5  # 0.1 * 470.9e+6 (2014 Electricity Sector)
  csp: false
  renewable_carriers: [solar, onwind, offwind-ac, offwind-dc, hydro]
  
  extendable_carriers:
    Generator: [CCGT, OCGT, coal, nuclear]
    StorageUnit: [battery] 
    #Store: [battery]
    #Link: []
    
  buses:
    RSA:
      OCGT: [RSA]
      CCGT: [RSA]
      coal: [RSA]
      nuclear: [RSA]
    9-supply: 
      OCGT: [GAUTENG, WESTERN CAPE, KZN, EASTERN CAPE] # Saldana Bay, Richards Bay, Coega
      CCGT: [GAUTENG, WESTERN CAPE, KZN, EASTERN CAPE]
      coal: [GAUTENG, LIMPOPO] # JOhannesburg, Waterberg
      nuclear: [EASTERN CAPE, WESTERN CAPE] # Thyspunt, Koeberg      
    27-supply:
      OCGT: [JOHANNESBURG, WEST COAST, EMPANGENI, PORT ELIZABETH] # Saldana Bay, Richards Bay, Coega
      CCGT: [JOHANNESBURG, WEST COAST, EMPANGENI, PORT ELIZABETH]
      coal: [JOHANNESBURG, WATERBERG]
      nuclear: [PORT ELIZABETH, PENINSULA] # Thyspunt, Koeberg
  
  BAU_mincapacities:
    nuclear: 10000
    coal: 10000
  
  SAFE_reservemargin: 0.1

  operational_reserve: # like https://genxproject.github.io/GenX/dev/core/#Reserves
    activate: false
    epsilon_load: 0.02 # share of total load
    epsilon_vres: 0.02 # share of total renewable supply
    contingency: 0 # fixed capacity in MW

  max_hours:
    battery: 3
    H2: 10

respotentials:
  # Gives us ball-park the available areas the IWES study reports
  landusetype_percent:
    wind:
      - [[7, 8, 9, 41], 80]
      # - [[5, 6], 50]
      # - [[11, 12, 14, 15], 10]
    solar:
      - [[7, 8, 9, 41], 80]
      # - [[11, 12, 14, 15], 50]
      # - [[46, 47, 51, 56, 64, 68, 72], 10]

  capacity_per_sqm:
    onwind: 5   # half of 10 (IWES)
    solar: 16.5 # half of 33 (IWES)

  source: eskom_actuals

hydro_inflow:
  source: eskom actuals
  disable: true
  countries: [ZA, MZ]
  cutout: za-mz-2012

lines:
  v_nom: 380.
  #type: 'Al/St 240/40 4-bundle 380.0'
#lines:
  types:
    220.: "Al/St 240/40 2-bundle 220.0"
    300.: "Al/St 240/40 3-bundle 300.0"
    380.: "Al/St 240/40 4-bundle 380.0"
  dc_type: "DC_custom_linetype"
  s_max_pu: 0.7
  s_nom_factor: 0.7
  s_nom_max: .inf
  length_factor: 1.25
  under_construction: "zero" # 'zero': set capacity to zero, 'remove': remove, 'keep': with full capacity

links:
  p_max_pu: 1.0
  p_nom_max: .inf
  include_tyndp: true
  under_construction: "zero" # 'zero': set capacity to zero, 'remove': remove, 'keep': with full capacity
  # costs
  s_nom_factor: 0.7
  length_factor: 1.25

augmented_line_connection:
  add_to_snakefile: true  # If True, includes this rule to the workflow
  connectivity_upgrade: 2  # Min. lines connection per node, https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.connectivity.edge_augmentation.k_edge_augmentation.html#networkx.algorithms.connectivity.edge_augmentation.k_edge_augmentation
  new_line_type: ["HVAC", "HVDC"]  # Expanded lines can be either ["HVAC"] or ["HVDC"] or both ["HVAC", "HVDC"]
  min_expansion: 1  # [MW] New created line expands by float/int input
  min_DC_length: 600  # [km] Minimum line length of DC line

costs:
  # costs come from data/technology_costs.xlsx
  discountrate: 0.08
  year: 2030
  # Marginal and capital costs can be overwritten
  # capital_cost:
  #   Wind: Bla
  marginal_cost: #
    solar: 0.01
    onwind: 0.015
    #offwind: 0.015 
    #PV: 0.01
    #Wind: 0.015
  USD_to_EUR: 0.7532
  EUR_to_ZAR: 15.63
  load_shedding: 100000 #R100/kWh
  fill_values:
    FOM: 0
    VOM: 0
    efficiency: 1
    fuel: 0
    investment: 0
    lifetime: 25
    "CO2 intensity": 0
    "discount rate": 0.07

  emission_prices: # only used with the option Ep (emission prices)
    # Externality costs from Integrated Energy Plan by the ZA DOE
    co2: 0.27e+3
    sox: 7.6e+3
    nox: 4.5e+3
    hg: 41484.e-6 # is also part of the excel sheet
    particulate: 11.3e+3

tsam_clustering:
  normed: true
  extremePeriodMethod: 'None'
  rescaleClusterPeriods: False
  hoursPerPeriod: 24
  clusterMethod: 'hierarchical'

solving:
  tmpdir: /tmp
  options:
    clip_p_max_pu: 1.e-2
    load_shedding: true
    noisy_costs: true
    skip_iterations: True
    min_iterations: 1
    max_iterations: 1
    formulation: kirchhoff
    # max_iterations: 1
    # nhours: 10
  solver:
    name: xpress
    lpflags: 4
    crossover: 0
    # BarConvTol: 1.e-5
    # FeasibilityTol: 1.e-6
    # LogToConsole: 0
    # OutputFlag: 1

plotting:
  map:
    figsize: [7, 7]
    boundaries: [14, 34, -35, -20] #[x1,x2,y1,y2]
    p_nom:
      bus_size_factor: 5.e+4
      linewidth_factor: 1.e+3 # 1.e+3  #3.e+3

  costs_max: 800

  vre_techs: ["Wind", "PV"]
  conv_techs: ["OCGT", "CCGT", "nuclear", "coal"]
  storage_techs: ["hydro", "CAES", "battery", "PHS", "hydro+PHS"]
  store_techs: ["Li ion", "water tanks"]
  load_carriers: ["AC load", "heat load", "Li ion load"]
  AC_carriers: ["AC line", "AC transformer"]
  link_carriers: ["DC line", "Converter AC-DC"] 
  heat_links: ["heat pump", "resistive heater", "CHP heat", "CHP electric",
               "gas boiler", "central heat pump", "central resistive heater", "central CHP heat",
               "central CHP electric", "central gas boiler"]
  heat_generators: ["gas boiler", "central gas boiler", "solar thermal collector", "central solar thermal collector"]
  tech_colors:
    "onwind": "#235ebc"
    "onshore wind": "#235ebc"
    "offwind": "#6895dd"
    "offwind-ac": "#6895dd"
    "offshore wind": "#6895dd"
    "offshore wind ac": "#6895dd"
    "offwind-dc": "#74c6f2"
    "offshore wind dc": "#74c6f2"
    "hydro": "#08ad97"
    "hydro+PHS": "#08ad97"
    "PHS": "#08ad97"
    "hydro reservoir": "#08ad97"
    "hydroelectricity": "#08ad97"
    "ror": "#4adbc8"
    "run of river": "#4adbc8"
    "solar": "#f9d002"
    "solar PV": "#f9d002"
    "solar thermal": "#ffef60"
    "biomass": "#0c6013"
    "solid biomass": "#06540d"
    "biogas": "#23932d"
    "waste": "#68896b"
    "geothermal": "#ba91b1"
    "OCGT": "#d35050"
    "gas": "#d35050"
    "natural gas": "#d35050"
    "CCGT": "#b20101"
    "nuclear": "#ff9000"
    "coal": "#707070"
    "lignite": "#9e5a01"
    "oil": "#262626"
    "H2": "#ea048a"
    "hydrogen storage": "#ea048a"
    "battery": "#b8ea04"
    "Electric load": "#f9d002"
    "electricity": "#f9d002"
    "lines": "#70af1d"
    "transmission lines": "#70af1d"
    "AC-AC": "#70af1d"
    "AC line": "#70af1d"
    "links": "#8a1caf"
    "HVDC links": "#8a1caf"
    "DC-DC": "#8a1caf"
    "DC link": "#8a1caf"
    "load_shedding": "#FF0000"
  nice_names:
    OCGT: "Open-Cycle Gas"
    CCGT: "Combined-Cycle Gas"
    offwind-ac: "Offshore Wind (AC)"
    offwind-dc: "Offshore Wind (DC)"
    onwind: "Onshore Wind"
    solar: "Solar"
    PHS: "Pumped Hydro Storage"
    hydro: "Reservoir & Dam"
    battery: "Battery Storage"
    H2: "Hydrogen Storage"
    lines: "Transmission Lines"
    ror: "Run of River"
