name: pypsa-za
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - six
  - snakemake
  - numpy
  - pyomo<6.1
  - scipy
  - pandas>=0.22.0
  - xlrd
  - matplotlib
  - seaborn
  - networkx>=1.10
  - netcdf4
  - xarray
  - pytables

  # Include ipython so that one does not inadvertently drop out of the conda
  # environment by calling ipython
  - ipython

  # GIS dependencies have to come all from conda-forge
  - conda-forge::libgdal
  - conda-forge::fiona
  - conda-forge::pyproj
  - conda-forge::pyshp
  - conda-forge::geopandas
  - conda-forge::rasterstats
  - conda-forge::rasterio
  - conda-forge::shapely

  - pip:
    - pypsa>=0.13,<0.18
    - vresutils>=0.2.4
    - countrycode
