# PyPSA-RSA Updated Environment File
# Updated to match PyPSA-EUR proven versions from linux-64.lock.yaml
# This ensures complete compatibility and stability

name: pypsa-rsa
channels:
  - conda-forge
  - bioconda
  - gurobi
  - nrel

dependencies:
  # Core Python (PyPSA-EUR version)
  - python=3.12.10
  - pip

  # Core PyPSA ecosystem (PyPSA-EUR versions)
  - pypsa=0.34.1
  - numpy=1.26.4
  - pandas=2.2.3
  - scipy=1.15.2
  - networkx=3.4.2
  - linopy=0.5.5

  # Workflow management (PyPSA-EUR versions)
  - snakemake-minimal=9.3.4
  - snakemake-executor-plugin-slurm=1.2.5
  - snakemake-executor-plugin-cluster-generic=1.0.9
  - ruamel.yaml
  - memory_profiler=0.61.0

  # Geographic and GIS packages (PyPSA-EUR versions)
  - geopandas=1.0.1
  - shapely=2.0.7
  - fiona=1.10.1
  - pyproj=3.7.1
  - cartopy=0.24.0
  - geos=3.13.1
  - gdal=3.10.3
  - rasterio=1.4.3
  - rioxarray=0.19.0
  - geopy=2.4.1

  # Data handling (PyPSA-EUR versions)
  - xarray=2025.4.0
  - netcdf4=1.7.2
  - openpyxl=3.1.5
  - xlrd=2.0.1
  - pytables=3.10.2
  - lxml=5.4.0

  # Scientific computing (PyPSA-EUR versions)
  - matplotlib=3.9.1
  - matplotlib-base=3.9.1
  - seaborn=0.13.2
  - numexpr=2.10.2
  - bottleneck=1.4.2
  - dask=2025.4.1
  - distributed=2025.4.1

  # Energy system modeling (PyPSA-EUR versions)
  - atlite=0.4.1
  - powerplantmatching=0.7.1
  - earth-osm
  - country_converter=1.2
  - cdsapi=0.7.6
  - entsoe-py=0.6.18

  # Optimization and solvers (PyPSA-EUR versions)
  - pyomo
  - highspy=1.10.0
  - glpk=5.0
  - ipopt=3.14.17
  - coin-or-cbc=2.10.12
  - gurobi

  # Additional scientific libraries (PyPSA-EUR versions)
  - scikit-learn=1.6.1
  - statsmodels=0.14.4
  - joblib=1.5.0

  # Plotting and visualization (PyPSA-EUR versions)
  - contextily
  - descartes=1.1.0
  - folium=0.19.5
  - plotly  # Available via pip
  - bokeh=3.7.3

  # Development and Jupyter (PyPSA-EUR versions)
  - jupyterlab=4.4.2
  - jupyter=1.1.1
  - ipykernel=6.29.5
  - ipython=9.2.0
  - ipywidgets=8.1.7

  # Code quality (PyPSA-EUR versions)
  - pre-commit=4.2.0
  - pylint=3.3.7
  - ruff=0.11.9

  # Utilities (PyPSA-EUR versions)
  - tqdm=4.67.1
  - psutil=7.0.0
  - pytz=2025.2
  - python-dateutil=2.9.0
  - requests=2.32.3
  - urllib3=2.4.0

  # File format support (PyPSA-EUR versions)
  - h5py  # For HDF5 files
  - pyarrow=20.0.0  # For Parquet files
  - fastparquet  # Alternative Parquet engine

  # Geographic data formats
  - geojson=3.2.0
  - pyshp=2.3.1

  # Additional PyPSA-RSA specific packages
  - reverse-geocode=1.4.1
  - pydoe2=1.3.0

  # System libraries (important for compatibility)
  - libgdal-core=3.10.3
  - proj=9.6.0
  - geos=3.13.1
  - libspatialite=5.1.0

  - pip:
    # Packages that work better via pip
    - tsam>=2.3.6
    - chaospy
    - plotly>=5.0.0
    - hvplot
    - panel
    
    # PyPSA-RSA specific pip packages
    - git+https://github.com/davide-f/google-drive-downloader@master
    - git+https://github.com/FRESNA/vresutils@master